gormlog: true
ginmode: "debug"

autotls: false
domain: ""
email: ""

mailgundomail: ""
mailgunkey: ""

mysql:
  username: ""
  password: ""
  addr: ""
  name: ""

log:
  path: ""
  filename: ""

commodityprice1: 1200
commodityprice2: 1000
commodityprice3: 800
freight: 60